apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_REPO'
    targetRevision: HEAD
    path: manifests/nginx  # Adjust this to the correct folder
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
